### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by AlvaroH2001** [UNLV-CS472-672/2024-S-GROUP4-SMTK#149]
Start to populate the events page with content
### Description
The events page is bare and empty and needs to be populated with content to showcase the idea of it being a hub for announcements, alerts, and reminders.

### Expected Behavior
An area where you'd be able to see upcoming and past events that were either shared by someone working from the healthcare location or from the user themselves. 

### Actual Behavior
It's empty.

### Possible Solution
Implement the expected behavior.

**Comment by tbg510** [comment]
Planning on working on this one when I have time, if you haven't started already.
