### ISSUE TITLE
Games

### ISSUE THREAD

**Issue by AlvaroH2001** [UNLV-CS472-672/2024-S-GROUP4-SMTK#153]
Start to populate the games page with content
### Description
The Games page currently looks bare and empty, it needs to be filled with content to best show the vision of the quality and quantity of games that would eventually be offered.

### Expected Behavior
Go into the page and be able to see various interactive components that showcase the idea of what the games section would be. Perhaps a tab for single player and multiplayer games and then games that are within each tab.

### Actual Behavior
It's empty.

### Possible Solution
Implement the expected behavior.

**Comment by junxjr** [comment]
I can work on games page
