### ISSUE TITLE
Application Flow Chart

### ISSUE THREAD

**Issue by aiharc1** [UNLV-CS472-672/2024-S-GROUP4-SMTK#18]
Flowchart on how application will flow into other components. How data is connected to app.

**Comment by jusasin** [comment]
Here is the link to the current flow chart we have so far. [https://app.diagrams.net/#G1qII-L5OBM7nbPNOoa-2KCIZoMfKkQxGY#%7B%22pageId%22%3A%22sX_SItcTKi9JSew_dXxW%22%7D](url)

**Comment by aiharc1** [comment]
Link to see the flow chart. Please be sure to open using flow.io

https://drive.google.com/file/d/1qII-L5OBM7nbPNOoa-2KCIZoMfKkQxGY/view?usp=sharing
