### ISSUE TITLE
Set up Firebase for chat room backend

### ISSUE THREAD

**Issue by blake-gilmore** [UNLV-CS472-672/2024-S-GROUP4-SMTK#44]

**Comment by jusasin** [comment]
Instead of using Firebase, 39Otsu and I were talking about just using MongoDB. This is so that we have just one database that we need to worry about, instead of having to use Firebase and Mongo. Will look into it more!

**Comment by blake-gilmore** [comment]
Sounds good, I'm going to go ahead and close this one.
