### ISSUE TITLE
Write out diagram for chat room implementation

### ISSUE THREAD

**Issue by blake-gilmore** [UNLV-CS472-672/2024-S-GROUP4-SMTK#45]

**Comment by junxjr** [comment]
Continued from where Justin left off on the flow chart. 

Finished the diagram for chat room implementation. The flow chart shows how the chatroom is going to connect with the database from the user login page. 

Note: Will be adding/changing the chart after we start the actually implementation with the code. 

![Image](https://github.com/UNLV-CS472-672/2024-S-GROUP4-SMTK/assets/156875726/e5804d24-c4c5-4479-977a-b20475e28da9)
