### ISSUE TITLE
Start working on test suite

### ISSUE THREAD

**Issue by blake-gilmore** [UNLV-CS472-672/2024-S-GROUP4-SMTK#47]

**Comment by blake-gilmore** [comment]
JMeter for load testing

**Comment by blake-gilmore** [comment]
Document a testing strategy that can best handle our needs in NextJS. May be helpful to find a short list of common testing suites and strategies, write some pros and cons about them, and decide what's easiest for what we're trying to do.

- Create a testing folder in our repo
- Create an instructions markdown for the proposed testing strategy
- List steps to create, debug, and test NextJS tests.

**Comment by AlvaroH2001** [comment]
Testing out the functionality of jest.
