### ISSUE TITLE
Expand test coverage to 90%

### ISSUE THREAD

**Issue by blake-gilmore** [UNLV-CS472-672/2024-S-GROUP4-SMTK#58]
- [ ] First we need to split up the testable components into 3rds
- [x] Wait for PR to get the test suite
- [ ] Get them files tested

**Comment by blake-gilmore** [comment]
@AlvaroH2001 Please post a screenshot of the test results here when you get the chance so we can split it into 3rds when you get the chance.

**Comment by blake-gilmore** [comment]
Current coverage

![Image](https://github.com/UNLV-CS472-672/2024-S-GROUP4-SMTK/assets/80655017/c88de3c0-d941-4133-a218-16d56f4af3c9)

**Comment by blake-gilmore** [comment]
I'm currently working on adding tests to the db folder and the HoverButton component

**Comment by AlvaroH2001** [comment]
Going to write a test for the TopBar component and accountCreation page
