### ISSUE TITLE
Check for first/last name in user/password

### ISSUE THREAD

**Issue by aiharc1** [UNLV-CS472-672/2024-S-GROUP4-SMTK#72]
We want to disallow usage of first or last name in the username or password fields for security reasons. 

We initially attemtped to prevent this in a past issue, however we did not realize it was only for case sensitive.
e.g.
first name: **Alpha**
last name: Bravo
username: Alpha //REJECTED
                  alpha // previously allowed
                  alpHA // previously allowed
                  
now it will reject all variations. 
username: Alpha //REJECTED
                  alpha //REJECTED
                  alpHA //REJECTED
                  
We also need to add a check where username!=password

**Comment by salazw1** [comment]
PR #71 fixes this issue.
